apiVersion: v1
data:
  name: cWRyYW50
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9xZHJhbnQuZ2l0aHViLmlvL3FkcmFudC1oZWxt
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: qdrant
  namespace: argocd
type: Opaque